version: "3.9"  # optional since v1.27.0

#! ================ Network Part ======================
networks:
  my-network:
    driver: bridge
    
    
#! ================ Memory Part ======================

volumes:

  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/gmary/data/
      o: bind

  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/gmary/data/
      o: bind

#! ================ Service Proposed ======================

services:
  
  mariadb:
    container_name: mariadb_docker
    image: mariadb
    build: ./requirements/mariadb
    restart: always
    networks:
      - my-network
    ports: 
      - "3306:3306"
    # expose:
    #   - "3306:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress_docker
    image: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - my-network
    # ports: 
    #   - "9000:9000"
    expose:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html/
    env_file:
      - .env
  
  nginx:
    container_name: nginx_docker
    image: nginx
    build: ./requirements/nginx
    restart: always
    networks:
      - my-network
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html/
    env_file:
      - .env