version: "3.9"  # optional since v1.27.0

#! ================ Network Part ======================
network:

#! ================ Memory Part ======================
volumes:

#! ================ Service Proposed ======================
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env