version: "3.9"  # optional since v1.27.0

#! ================ Network Part ======================
network:

#! ================ Memory Part ======================
volumes:

#! ================ Service Proposed ======================
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: "443:443"